moved methods, constructors and operators to cpp, defined arithm, need to fix undefined reference to `lcm_list(std::__cxx11::list<int, std::allocator<int> >)'